image: ghcr.io/smart-building-manager/{arch}-hassio-cli
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  armhf: ghcr.io/home-assistant/armhf-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  i386: ghcr.io/home-assistant/i386-base:3.20
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
# cosign:
#   base_identity: https://github.com/home-assistant/docker-base/.*
#   identity: https://github.com/home-assistant/plugin-cli/.*
args:
  CLI_VERSION: 4.36.2
  RLWRAP_VERSION: 0.46.1
labels:
  io.hass.type: cli
  org.opencontainers.image.title: Home Assistant CLI Plugin
  org.opencontainers.image.description: Home Assistant Supervisor plugin for CLI
  org.opencontainers.image.source: https://github.com/home-assistant/plugin-cli
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
